# Generated by Django 4.2.18 on 2025-04-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepregnancy',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='prepregnancy',
            name='time_update',
        ),
    ]
