# Generated by Django 4.2.18 on 2025-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0002_remove_prepregnancy_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepregnancy',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prepregnancy',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
