# Generated by Django 4.2.18 on 2025-04-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0003_prepregnancy_slug_alter_prepregnancy_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepregnancy',
            name='url',
        ),
    ]
