# Generated by Django 4.2.18 on 2025-04-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0004_remove_prepregnancy_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
