# Generated by Django 4.2.18 on 2025-04-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0005_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepregnancy',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='parentroadmapapp.menu'),
        ),
    ]
