# Generated by Django 4.2.18 on 2025-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0007_alter_prepregnancy_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
