# Generated by Django 4.2.18 on 2025-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0008_remove_menu_slug_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL'),
        ),
    ]
