# Generated by Django 4.2.18 on 2025-05-05 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0010_alter_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepregnancy',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepregnancy_menu', to='parentroadmapapp.menu'),
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_menu', to='parentroadmapapp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Parenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parenting_menu', to='parentroadmapapp.menu')),
            ],
        ),
    ]
