# Generated by Django 4.2.18 on 2025-05-28 09:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentroadmapapp', '0011_alter_prepregnancy_menu_pregnancy_parenting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parenting',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='prepregnancy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
